language: python
branches:
  only:
    - master
    - /\d+\.\d+\..+/
install:
  - pip install numpy scikit-learn
script: nosetests gmr
notifications:
  recipients:
    - afabisch@informatik.uni-bremen.de
  email:
    on_success: change
    on_failure: always
