language: python
branches:
  only:
    - master
    - /\d+\.\d+\..+/
install:
  - pip install numpy scipy matplotlib
script: nosetests gmr
notifications:
  recipients:
    - alexander.fabisch@dfki.de
  email:
    on_success: change
    on_failure: always
